---

- hosts: all
  user: root
  gather_facts: no
  vars:
    domain: hattrick.lab
    rhv_vm_auth_url: https://rhvm.hattrick.lab/ovirt-engine/api
    rhv_vm_template: rhel84-template
    rhv_vm_instance_type: small
    rhv_vm_basename: rhel-vm
    server_cnt: 2
  tasks:
    - name: Authenticate to engine to obtain SSO token
      include_role:
        name: redhatgov.rhv_vm
        tasks_from: login

    - name: Create a RHV VM
      vars:
        rhv_vm_hostname: "{{ rhv_vm_basename }}-{{ item  }}"
      include_role:
        name: redhatgov.rhv_vm
        tasks_from: create_rhv_vm
      with_sequence: start=1 end={{ server_cnt }}

    - name: Revoke SSO token
      include_role:
        name: redhatgov.rhv_vm
        tasks_from: revoke_token

