---

- hosts: rhvm
  user: root
  gather_facts: no
  vars:
    rhv_vm_auth_url: https://rhvm.hattrick.lab/ovirt-engine/api
    rhv_vm_cluster: Default
    domain: hattrick.lab
    rhv_vm_basename: rhel-vm
    server_cnt: 3
  tasks:
   - name: Login to RHV
     include_role:
       name: redhatgov.rhv_vm
       tasks_from: login

   - name: Delete a RHV VM
     vars:
       rhv_vm_hostname: "{{ rhv_vm_basename }}-{{ item }}"
     include_role:
       name: redhatgov.rhv_vm
       tasks_from: teardown_rhv_vm
     with_sequence: start=1 end={{ server_cnt }}

   - name: Revoke Token
     include_role:
       name: redhatgov.rhv_vm
       tasks_from: revoke_token

   - name: Remove {{ rhv_vm_hostname }} from hosts file
     delegate_to: localhost
     connection: local
     become: true
     vars:
       rhv_vm_hostname: "{{ rhv_vm_basename }}-{{ item }}"
     lineinfile:
       path: /etc/hosts
       state: absent
       regexp: '.*{{ rhv_vm_hostname }}.{{ domain }} {{ rhv_vm_hostname }}'
     with_sequence: start=1 end={{ server_cnt }}
